config/routes.rb
Rails.application.routes.draw do
  resources :performances
  root 'performances#index'
  get 'uploader/new'

  post 'uploader/create'

  get 'samples/upload'

  post 'graph/index'
  get 'graph/index/' => 'graph#index'
  get 'graph/search'

  get 'acceleration/index/:performance' => 'acceleration#index', format: 'json'
  get 'gyroscope/index/:performance' => 'gyroscope#index', format: 'json'

end

app/models/acceleration.rb
class Acceleration
  def initialize(sample)
    @sample = sample
  end

  def acceleration
    Math.sqrt(x_squared + y_squared + z_squared).round(5)
  end

  def square(number)
    number ** 2
  end

  def x_squared
    square(@sample.acceleration_x)
  end

  def y_squared
    square(@sample.acceleration_y)
  end

  def z_squared
    square(@sample.acceleration_z)
  end

  def performance_index
    @sample.performance_index
  end

  def timestamp
    performance_index/208
  end

end

app/models/gyroscope.rb
class Gyroscope
  def initialize(sample)
    @sample = sample
  end

  def gyroscope_data
    # Math.sqrt(x_squared + y_squared + z_squared).round(5)
    x_squared
  end

  def square(number)
    number ** 2
  end

  def x_squared
    square(@sample.gyroscope_x)
  end

  def y_squared
    square(@sample.gyroscope_y)
  end

  def z_squared
    square(@sample.gyroscope_z)
  end


  def performance_index
    @sample.performance_index
  end

end

app/models/performance.rb
class Performance < ActiveRecord::Base
  has_many :samples
  validates :name, presence: true
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :performance

  def acceleration_x
    accel_x || 0
  end

  def acceleration_y
    accel_y || 0
  end

  def acceleration_z
    accel_z || 0
  end

  def gyroscope_x
    gyro_x || 0
  end

  def gyroscope_y
    gyro_y || 0
  end

  def gyroscope_z
    gyro_z || 0
  end




end

app/models/uploader.rb
class Uploader
  def initialize(path, performance_id)
    performance = Performance.where('id = ?', performance_id).first
    performance.battery_voltage = CSV.read(path, headers: true).headers.last
    performance.save
    SmarterCSV.process(path, {chunk_size: 10000}) do |chunk|
     samples = chunk.map do |d|
       Sample.new(
         performance_index: d[:t],
         performance_id: performance_id,
         accel_x: d[:x],
         accel_y: d[:y],
         accel_z: d[:z],
         gyro_x: d[:rx],
         gyro_y: d[:ry],
         gyro_z: d[:rz],
         )
     end
     Sample.import samples
   end
 end

end

app/controllers/acceleration_controller.rb
class AccelerationController < ApplicationController

  def index
    performance = Performance.find(params[:performance])
    @accelerations = performance.samples.map {|s| Acceleration.new(s) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require "csv"

end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
    @start = params[:start] || 0
    @end = params[:end] || 500
    @url = "/acceleration/index/#{@start}/#{@end}"
  end

  def search

  end
end

app/controllers/gyroscope_controller.rb
class GyroscopeController < ApplicationController

  def index
    performance = Performance.find(params[:performance])
    @gyroscope_data = performance.samples.map {|s| Gyroscope.new(s) }
  end

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_performance, only: [:show, :edit, :update, :destroy]

  # GET /performances
  # GET /performances.json
  def index
    @performances = Performance.all
  end

  # GET /performances/1
  # GET /performances/1.json
  def show
    @accel_url = "/acceleration/index/#{@performance.id}"
    @gyro_url = "/gyroscope/index/#{@performance.id}"
  end

  # GET /performances/new
  def new
    @performance = Performance.new
  end

  # GET /performances/1/edit
  def edit
  end

  # POST /performances
  # POST /performances.json
  def create
    @performance = Performance.new(performance_params)

    respond_to do |format|
      if @performance.save
        format.html { redirect_to @performance, notice: 'Performance was successfully created.' }
        format.json { render :show, status: :created, location: @performance }
      else
        format.html { render :new }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performances/1
  # PATCH/PUT /performances/1.json
  def update
    respond_to do |format|
      if @performance.update(performance_params)
        format.html { redirect_to @performance, notice: 'Performance was successfully updated.' }
        format.json { render :show, status: :ok, location: @performance }
      else
        format.html { render :edit }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performances/1
  # DELETE /performances/1.json
  def destroy
    @performance.destroy
    respond_to do |format|
      format.html { redirect_to performances_url, notice: 'Performance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance
      @performance = Performance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def performance_params
      params.require(:performance).permit(:name, :date)
    end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  def new
    @performances = Performance.all
  end

  def create
      file = params[:file].path
      if !params[:performance].empty?
        Uploader.new(file, params[:performance])
      elsif params[:performance_name]
        date = params[:performance_date].empty? ? Time.now.to_date : params[:performance_date]
        p = Performance.create(name: params[:performance_name], date: date)
        Uploader.new(file, p.id)
      end
  end
end

app/helpers/acceleration_helper.rb
module AccelerationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/graph/index.html.erb
<svg id="graph", data-url="<%= @url %>">
</svg>

<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

// var formatDate = d3.time.format("%d-%b-%y");

var x = d3.scale.linear()
    .range([0, width]);


var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.date); })
    .y(function(d) { return y(d.acceleration); });

var svg = d3.select("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var url = d3.select("svg").attr("data-url")

d3.json(url, function (data) {
    data.forEach(function(d) {
      // d.date = formatDate.parse(d.date);
      d.date = +d.date;
      d.acceleration = +d.acceleration;
      return d;
    });


  x.domain(d3.extent(data, function(d) { return d.date; }));
  y.domain(d3.extent(data, function(d) { return d.acceleration; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Force(g)");

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line);
});




</script>

app/views/graph/search.html.erb
<div>
<h3>Select your starting and ending coordinates</h3>
  <%= form_tag graph_index_path do %>
    <%= text_field_tag :start %>
    <%= text_field_tag :end %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aerialometer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/performances/_acceleration_graph.html.erb
<svg id="graph", data-accel-url="<%= @accel_url %>", data-gyro-url="<%= @gyro_url %>">
</svg>

<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

// var formatDate = d3.time.format("%d-%b-%y");

var x = d3.scale.linear()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.date); })
    .y(function(d) { return y(d.acceleration); });

var svg = d3.select("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var accelUrl = d3.select("svg").attr("data-accel-url");
var gyroUrl = d3.select("svg").attr("data-gyro-url");

function displayData(url) {
  d3.json(url, function (data) {
      data.forEach(function(d) {
        // d.date = formatDate.parse(d.date);
        d.date = +d.date;
        d.acceleration = +d.acceleration;
        return d;
      });


    x.domain(d3.extent(data, function(d) { return d.date; }));
    y.domain(d3.extent(data, function(d) { return d.acceleration; }));

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
      .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text("Force(g)");

    svg.append("path")
        .datum(data)
        .attr("class", "line")
        .attr("d", line);
  });
};

function clearData() {
  svg.selectAll("*").remove();
};

displayData(accelUrl);

$( function() {
  $("#change-data").change(function() {
    var value = $("#change-data").val();
    if (value === "acceleration") {
      clearData();
      displayData(accelUrl);
    } else {
      clearData();
      displayData(gyroUrl);
    };
  });
});




</script>

app/views/performances/_aerialometer_graph.html.erb
<svg id="graph", data-accel-url="<%= @accel_url %>", data-gyro-url="<%= @gyro_url %>">
</svg>

<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var x = d3.scale.linear()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.time/208); })
    .y(function(d) { return y(d.acceleration); });

var svg = d3.select("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var accelUrl = d3.select("svg").attr("data-accel-url");
var gyroUrl = d3.select("svg").attr("data-gyro-url");

function displayData(url) {
  d3.json(url, function (data) {
      data.forEach(function(d) {
        d.time = +d.time;
        d.acceleration = +d.acceleration;
        return d;
      });


    x.domain(d3.extent(data, function(d) { return d.time/208; }));
    y.domain(d3.extent(data, function(d) { return d.acceleration; }));

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
      .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text("Force(g)");

    svg.append("path")
        .datum(data)
        .attr("class", "line")
        .attr("d", line);
  });
};

function clearData() {
  svg.selectAll("*").remove();
};

displayData(accelUrl);

$( function() {
  $("#change-data").change(function() {
    var value = $("#change-data").val();
    if (value === "acceleration") {
      clearData();
      displayData(accelUrl);
    } else {
      clearData();
      displayData(gyroUrl);
    };
  });
});




</script>

app/views/performances/_form.html.erb
<%= form_for(@performance) do |f| %>
  <% if @performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performance.errors.count, "error") %> prohibited this performance from being saved:</h2>

      <ul>
      <% @performance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performances/edit.html.erb
<h1>Editing Performance</h1>

<%= render 'form' %>

<%= link_to 'Show', @performance %> |
<%= link_to 'Back', performances_path %>

app/views/performances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Performances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td><%= performance.name %></td>
        <td><%= performance.date %></td>
        <td><%= link_to 'Show', performance %></td>
        <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
        <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Upload Data', uploader_new_path %>

app/views/performances/new.html.erb
<h1>New Performance</h1>

<%= render 'form' %>

<%= link_to 'Back', performances_path %>

app/views/performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @performance.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @performance.date %>
</p>

<p>
  <strong>Battery Voltage:</strong>
  <%= @performance.battery_voltage %>
</p>

<% unless @performance.samples.empty? %>
  <%= render 'aerialometer_graph' %>
<% end %>

<div>
  Select Data to Display:
  <select id="change-data">
    <option value="acceleration">Acceleration</option>
    <option value="gyroscope">Gyroscope Data</option>
  </select>
</div>

<%= link_to 'Edit', edit_performance_path(@performance) %> |
<%= link_to 'Back', performances_path %>

app/views/samples/upload.html.erb
<h1>Samples#upload</h1>
<p>Find me in app/views/samples/upload.html.erb</p>

app/views/uploader/create.html.erb
<p>Thank you! Your file is being uploaded.</p>
<%= link_to "Go back to performances", performances_path %>

app/views/uploader/new.html.erb
<div>
<h3>Import a CSV File</h3>
  <%= form_tag uploader_create_path, multipart: true do %>
    <%= file_field_tag :file, required: true %>
    <h3> Add Performance <h3>
      <%= radio_button_tag(:select_performance, "Select Performance", checked: true) %>
      <%= label_tag(:select_performance, "Select Performance") %><br>
      <%= radio_button_tag(:select_performance, "Create New Performance") %>
      <%= label_tag(:select_performance, "Create New Performance") %><br>
    <%= select_tag :performance, options_from_collection_for_select(@performances, "id", "name"),  prompt: "Select performance", class: "performance_selection" %>
    <%= text_field_tag :performance_name, nil, placeholder: "Performance Name", class: "performance_creation" %>
    <%= date_field_tag :performance_date, nil, placeholder: "Select Date", class: "performance_creation" %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<script>
 $(function() {
  var creation_fields = $(".performance_creation");
  var select_menu = $(".performance_selection");
  var select_existing = $("#select_performance_Select_Performance");
  var create_new = $("#select_performance_Create_New_Performance");
  if (select_existing.is(':checked')) {
    creation_fields.hide();
    select_menu.show();
  } else {
    creation_fields.show();
    select_menu.hide();
  };
  select_existing.on('click', function () {
    if (select_existing.is(':checked')) {
      creation_fields.hide();
      select_menu.show();
    } else {
      creation_fields.show();
      select_menu.hide();
    };
  });
  create_new.on('click', function () {
    if (select_existing.is(':checked')) {
      creation_fields.hide();
      select_menu.show();
    } else {
      creation_fields.show();
      select_menu.hide();
    };
  });
});





</script>